export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE";

export const ADD_USER = "ADD_USER";
export const REMOVE_USER_FROM_STORE = "REMOVE_USER_FROM_STORE";
